# MAIN base
baseURL = "https://home-cloud.io/"
languageCode = "en-us"
title = "Home Cloud"
theme = "steady-bytes"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Features"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "FAQ"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Updates"
    url = "/blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Updates"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.info]
enableAddress = false
address = ""
enableEmail = true
email = "hello@home-cloud.io"
enablePhone = false
phone = ""

# Footer Social
[params.social]
enableFacebook = false
facebook = "#"
enableTwitter = false
twitter = "#"
enableGithub = true
github = "https://github.com/home-cloud-io"

[params.analytics]
plausibleDomain = "home-cloud.io"
plausibleSrc = "https://plausible.steady-bytes.com/js/script.js"

# Mastodon
[params.mastodon]
accounts = [ "https://mastodon.world/@jgkawell" ]

[params]

# Header
logo = "images/site-logo-purple.svg"

# Footer
footerTitle = "Keep up to date"
copyright1 = "All rights reserved"
copyright2 = "Copyright ©  <a href=\"https://steady-bytes.com/\" target=\"_blank\">Steady Bytes </a> {year}"

# Contact
email = "hello@home-cloud.io"
